# Generated by Django 3.2.6 on 2021-08-31 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('verified_account', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_host', models.BooleanField(default=False)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('public_email', models.BooleanField(default=False)),
                ('public_gender', models.BooleanField(default=False)),
                ('public_dob', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('interested_location', models.ManyToManyField(blank=True, default=None, to='misc.City')),
                ('travel_type', models.ManyToManyField(blank=True, default=None, to='misc.TravelType')),
                ('trip_interest', models.ManyToManyField(blank=True, default=None, to='misc.TripInterest')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=4)),
                ('usage', models.CharField(choices=[('Register', 'Register'), ('Forgot', 'Forgot')], default='Register', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
