# Generated by Django 3.2.6 on 2021-08-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
