# Generated by Django 3.2.6 on 2021-08-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_myuser_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sign_up_steps',
            field=models.CharField(choices=[('OTP Sent', 'OTP Sent'), ('OTP Verified', 'OTP Verified'), ('Password Set', 'Password Set'), ('Email Set', 'Email Set'), ('Profile Added', 'Profile Added'), ('Profile Added', 'Profile Added')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
