# Generated by Django 3.2.6 on 2021-09-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_temptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sign_up_steps',
            field=models.CharField(choices=[('OTP Sent', 'OTP Sent'), ('OTP Verified', 'OTP Verified'), ('Password Set', 'Password Set'), ('Email Set', 'Email Set'), ('Travel Type Set', 'Travel Type Set'), ('Travel Interest Set', 'Travel Interest Set'), ('Wander List Set', 'Wander List Set'), ('Profile Added', 'Profile Added')], max_length=20),
        ),
        migrations.AlterField(
            model_name='temptoken',
            name='usage',
            field=models.CharField(choices=[('Password', 'Password'), ('Profile', 'Profile'), ('Email', 'Email'), ('Travel Type', 'Travel Type'), ('Travel Interest', 'Travel Interest'), ('Wander List', 'Wander List')], default='Password', max_length=20),
        ),
    ]
