# Generated by Django 3.2.6 on 2021-09-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210901_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='sign_up_steps',
            field=models.CharField(choices=[('OTP Sent', 'OTP Sent'), ('OTP Verified', 'OTP Verified'), ('Password Set', 'Password Set'), ('Email Set', 'Email Set'), ('Profile Added', 'Profile Added'), ('Travel Type Set', 'Travel Type Set'), ('Trip Interest Set', 'Trip Interest Set'), ('Wander List Set', 'Wander List Set')], default='OTP Sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='temptoken',
            name='usage',
            field=models.CharField(choices=[('Password', 'Password'), ('Email', 'Email'), ('Profile', 'Profile'), ('Travel Type', 'Travel Type'), ('Travel Interest', 'Travel Interest'), ('Wander List', 'Wander List')], default='Password', max_length=20),
        ),
    ]
