# Generated by Django 3.2.6 on 2021-09-09 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_temptoken_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
