# Generated by Django 3.2.6 on 2021-09-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_temptoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sign_up_steps',
            field=models.CharField(choices=[('OTP Sent', 'OTP Sent'), ('OTP Verified', 'OTP Verified'), ('Password Set', 'Password Set'), ('Email Set', 'Email Set'), ('Profile Set', 'Profile Set'), ('Travel Type Set', 'Travel Type Set'), ('Trip Interest Set', 'Trip Interest Set'), ('Wander List Set', 'Wander List Set')], default='OTP Sent', max_length=20),
        ),
    ]
