# Generated by Django 3.2.6 on 2021-08-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_mattress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_of_stay',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stay',
            name='extra_mattress_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stay',
            name='number_of_extra_mattress_available',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stay',
            name='price_per_extra_mattress',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
