# Generated by Django 3.2.6 on 2021-09-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0002_auto_20210831_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='nearby',
            field=models.TextField(blank=True, null=True),
        ),
    ]
