# Generated by Django 3.2.6 on 2021-09-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0003_stay_nearby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='max_people_allowed',
        ),
    ]
