# Generated by Django 3.2.6 on 2021-09-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0004_remove_stay_max_people_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='number_of_extra_mattress_available',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='price_per_extra_mattress',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
