# Generated by Django 3.2.6 on 2021-09-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0005_auto_20210906_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='number_of_extra_mattress_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
