# Generated by Django 3.2.6 on 2021-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0006_alter_stay_number_of_extra_mattress_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Halt', 'Halt'), ('InActive', 'InActive')], default='Active', max_length=20),
        ),
    ]
