# Generated by Django 3.2.6 on 2021-09-06 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0007_stay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stayimage',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stay.stay'),
        ),
    ]
