# Generated by Django 3.2.6 on 2021-09-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0009_auto_20210906_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facilities',
            new_name='Facility',
        ),
    ]
