# Generated by Django 3.2.6 on 2021-09-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0010_rename_facilities_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearestHotSpots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='stay.stay')),
            ],
        ),
    ]
