# Generated by Django 3.2.6 on 2021-09-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0012_auto_20210906_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearesthotspots',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_locations', to='stay.stay'),
        ),
    ]
