# Generated by Django 3.2.6 on 2021-09-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0017_auto_20210907_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='accepted',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
