# Generated by Django 3.2.6 on 2021-09-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0018_auto_20210908_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
