# Generated by Django 3.2.6 on 2021-09-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0019_booking_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
