# Generated by Django 3.2.6 on 2021-09-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0020_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='members',
            new_name='guests',
        ),
    ]
