# Generated by Django 3.2.6 on 2021-09-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_booking_price_of_trip'),
        ('stay', '0021_rename_members_booking_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(default='some review', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='planner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.planner'),
        ),
    ]
