# Generated by Django 3.2.6 on 2021-09-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0023_remove_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
