# Generated by Django 3.2.6 on 2021-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0024_booking_cancellation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date_due_to_cancellation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
