# Generated by Django 3.2.6 on 2021-09-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0025_booking_end_date_due_to_cancellation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_date_due_to_cancellation',
        ),
    ]
