# Generated by Django 3.2.6 on 2021-09-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0026_remove_booking_end_date_due_to_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stay.booking'),
            preserve_default=False,
        ),
    ]
