# Generated by Django 3.2.6 on 2021-09-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0027_review_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stay',
        ),
    ]
