# Generated by Django 3.2.6 on 2021-09-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0028_remove_review_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(default='some text', max_length=256),
            preserve_default=False,
        ),
    ]
