# Generated by Django 3.2.6 on 2021-09-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0029_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='planner',
        ),
    ]
