# Generated by Django 3.2.6 on 2021-09-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0031_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='number_of_adults',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_children',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
