# Generated by Django 3.2.6 on 2021-09-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0032_auto_20210913_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='pet_friendly',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
