# Generated by Django 3.2.6 on 2021-09-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0035_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], default='Active', max_length=20),
        ),
    ]
