# Generated by Django 3.2.6 on 2021-09-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0036_alter_stay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='own_stay_booked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled By Host', 'Cancelled By Host'), ('Cancelled By User', 'Cancelled By User')], default='Pending', max_length=20),
        ),
    ]
