# Generated by Django 3.2.6 on 2021-09-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0037_auto_20210916_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='own_stay_booked',
        ),
    ]
