# Generated by Django 3.2.6 on 2021-09-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0039_booking_commission_at_time_of_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
