# Generated by Django 3.2.6 on 2021-09-23 13:22

from django.db import migrations, models
import stay.models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0040_remove_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(default='facilities/default.jpeg', upload_to=stay.models.facility_pic_upload_to),
        ),
    ]
