# Generated by Django 3.2.6 on 2021-08-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_booking_price_of_trip'),
        ('post', '0001_initial'),
        ('stay', '0002_auto_20210831_1021'),
        ('event', '0002_auto_20210831_1127'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='event_bookmarks',
            field=models.ManyToManyField(blank=True, default=None, to='event.Event'),
        ),
        migrations.AddField(
            model_name='profile',
            name='log_bookmarks',
            field=models.ManyToManyField(blank=True, default=None, to='trip.Log'),
        ),
        migrations.AddField(
            model_name='profile',
            name='planner_bookmarks',
            field=models.ManyToManyField(blank=True, default=None, to='trip.Planner'),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_bookmarks',
            field=models.ManyToManyField(blank=True, default=None, to='post.Post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stay_bookmarks',
            field=models.ManyToManyField(blank=True, default=None, to='stay.Stay'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trip_bookmarks',
            field=models.ManyToManyField(blank=True, default=None, to='trip.Trip'),
        ),
    ]
