# Generated by Django 3.2.6 on 2021-08-31 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import event.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('adult_entry_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_entry_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stag_entry_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('couple_entry_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eves_entry_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('seats', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('people_interested', models.ManyToManyField(blank=True, default=None, related_name='event_interested_people', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannerWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_wishlsit', to='trip.planner')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=event.models.file_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('members', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('planner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_planner', to='trip.planner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_book', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
