# Generated by Django 3.2.6 on 2021-08-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adult_entry_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='child_entry_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='couple_entry_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='eves_entry_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_adults',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_child',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_couple',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_eves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_stag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='stag_entry_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
