# Generated by Django 3.2.6 on 2021-09-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210902_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Live Screening', 'Live Screening'), ('InHouse Gathering', 'InHouse Gathering'), ('Concert', 'Concert'), ('Sports', 'Sports'), ('Party', 'Party'), ('Bon-Fire', 'Bon-Fire'), ('Open Field', 'Open Field')], max_length=50),
        ),
    ]
