# Generated by Django 3.2.6 on 2021-09-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_eventimage_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
