# Generated by Django 3.2.6 on 2021-09-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='members',
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_adults',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_child',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_couple',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_eves',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_stag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
