# Generated by Django 3.2.6 on 2021-09-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
