# Generated by Django 3.2.6 on 2021-09-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_booking_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], default='Active', max_length=20),
        ),
    ]
