# Generated by Django 3.2.6 on 2021-09-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_pay',
            field=models.PositiveIntegerField(default=2342),
            preserve_default=False,
        ),
    ]
