# Generated by Django 3.2.6 on 2021-09-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20210917_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_at_time_of_booking',
            field=models.PositiveIntegerField(default=25),
            preserve_default=False,
        ),
    ]
