# Generated by Django 3.2.6 on 2021-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='adult_entry_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
