# Generated by Django 3.2.6 on 2021-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20210907_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.CharField(default='Maharashtra', max_length=100),
            preserve_default=False,
        ),
    ]
