# Generated by Django 3.2.6 on 2021-09-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_booking_price_of_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Family', 'Family'), ('Friends', 'Friends'), ('Public', 'Public')], max_length=50),
        ),
    ]
