# Generated by Django 3.2.6 on 2021-09-24 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_city_province'),
        ('trip', '0004_alter_trip_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.traveltype'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='type_of_travel',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='public', max_length=50),
            preserve_default=False,
        ),
    ]
