# Generated by Django 3.2.6 on 2021-09-24 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20210924_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='number_of_travelers',
            new_name='number_of_travellers',
        ),
    ]
