# Generated by Django 3.2.6 on 2021-10-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_remove_trip_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfiles',
            name='user',
        ),
    ]
